print ("Hello World")
print ("Aekasit")
print ("Aekasit")
print ("Aekasit")
print ("Aekasit")
print ("Aekasit")
print ("Aekasit")
print ("Aekasit")
print ("Aekasit")
print ("Aekasit")
print ("Ramet")
